apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xh25iu6wg-java-quarkus
  janus-idp.io/tekton: xh25iu6wg-java-quarkus
  backstage.io/kubernetes-id: xh25iu6wg-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xh25iu6wg-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
